# Generated by Django 4.1.5 on 2023-02-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='power',
            options={'ordering': ['id'], 'verbose_name': 'OOO COMPLEX INSTALL', 'verbose_name_plural': 'OOO COMPLEX INSTALL'},
        ),
    ]
